In [217]:
import pandas as pd
import numpy as np

In [218]:
df=pd.read_csv("00 customer.csv")
df.sample(5)

    age  gender   review education purchased
19   97    Male     Poor        PG       Yes
49   25  Female     Good        UG        No
20   57  Female  Average    School       Yes
48   39  Female     Good        UG       Yes
8    65  Female  Average        UG        No

In [219]:
print(df['review'].unique())
print(df['education'].unique())
print(df['purchased'].unique())

['Average' 'Poor' 'Good']
['School' 'UG' 'PG']
['No' 'Yes']

In [220]:
df=df.iloc[:,2:]
df.sample(5)

     review education purchased
48     Good        UG       Yes
28     Poor    School        No
16     Poor        UG       Yes
45     Poor        PG       Yes
20  Average    School       Yes

In [221]:
x=df.iloc[:,0:2]
y=df.drop(x,axis='columns')
print(x.head())
print()
print()
print()
print(y.head())

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG



  purchased
0        No
1        No
2        No
3        No
4        No

In [222]:
from sklearn.preprocessing import OrdinalEncoder

In [223]:
oe = OrdinalEncoder(
    categories=[
        ['Poor', 'Average', 'Good'],
        ['School', 'UG', 'PG']
    ]
).set_output(transform='pandas')

In [224]:
x_encoded = oe.fit_transform(x)

print("Original Data:")
print(x.head())

print("\nEncoded Data:")
print(x_encoded.head())

Original Data:
    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

Encoded Data:
   review  education
0     1.0        0.0
1     0.0        1.0
2     2.0        2.0
3     2.0        2.0
4     1.0        1.0

In [225]:
from sklearn.preprocessing import LabelEncoder

In [226]:
le=LabelEncoder()
le.fit_transform(y)

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [227]:
le = LabelEncoder()
purchased = le.fit_transform(y)

y_df = pd.DataFrame(purchased, columns=['purchased'])
y_df

/usr/local/lib/python3.13/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

    purchased
0           0
1           0
2           0
3           0
4           0
5           1
6           0
7           1
8           0
9           1
10          1
11          1
12          0
13          0
14          1
15          0
16          1
17          1
18          0
19          1
20          1
21          0
22          1
23          0
24          1
25          0
26          0
27          0
28          0
29          1
30          0
31          1
32          1
33          1
34          0
35          1
36          1
37          1
38          0
39          0
40          0
41          1
42          1
43          0
44          0
45          1
46          0
47          1
48          1
49          0